[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true
npwire.workspace = true

anyhow.workspace = true
bytes.workspace = true
bytestring.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "io-util"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
transport.workspace = true
parking_lot = "0.12"
console-subscriber = "0.5"

local-ip-address = { version = "0.6.5", optional = true }
udt = { path = "../udt", optional = true }
mediator-proto = { path = "../mediator-proto", optional = true }

[features]
bin = ["dep:local-ip-address", "dep:udt", "dep:mediator-proto"]

[[bin]]
name = "client"
required-features = ["bin"]