[package]
name = "udt"
version = "0.1.0"
edition = "2024"

[dependencies]
udt-sys = { path = "../udt-sys" }
os_socketaddr = "0.2"
libc = "0.2"
cfg-if = "1"
tokio = { workspace = true, features = ["rt"] }
parking_lot = "0.12"
weak-table = "0.3"
rustix = { version = "1", features = ["fs"] }