[workspace]
resolver = "2"
members = [ "client", "noiseproxy", "npwire","server", "util"]

[workspace.dependencies]
util.path = "./util"
npwire.path = "./npwire"

anyhow = "1"
bytes = "1.10"
tokio = "1.43"
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
thiserror = "2"
bytestring = "1.4"
rand = "0.9"
