[package]
name = "udt-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1"
cfg-if = "1"
scc = "2.3"
bitflags = "2.9"
md-5 = "0.11.0-rc.0"
util.workspace = true

[build-dependencies]
cxx-build = "1"