[package]
name = "mediator-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { version = "0.14", features = ["server"] }
prost = "0.14"
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"