[package]
name = "utp-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1"

[build-dependencies]
cc = "1.2"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winsock2", "ws2def", "ws2tcpip"] }