[package]
name = "utp-sys"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1"
libc = "0.2"

[build-dependencies]
cc = "1.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Networking_WinSock"] }