[package]
name = "utp"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["time"] }
utp-sys.workspace = true

crossbeam = "0.8"
os_socketaddr = "0.2"
parking_lot = "0.12"
pin-weak = "1.1"
ringbuf = "0.4"