[package]
name = "udt-example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
udt = { path = "../udt" }
transport = { path = "../transport" }
tokio = { workspace = true, features = ["macros", "rt", "time", "io-util"] }