[package]
name = "player"
version.workspace = true
edition.workspace = true

[dependencies]
client.path = "../client"
transport = { path = "../transport", features = ["tokio"] }
mpv-sys.path = "./mpv-sys"

tracing-subscriber.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-util.workspace = true

winit = "0.30"
ctrlc = "3.5"
async-task = "4.7"
stable-vec = "0.4"