[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
npwire.workspace = true
transport = { path = "../transport", features = ["compio"] }

anyhow.workspace = true
bytes.workspace = true
bytestring.workspace = true
tokio = { workspace = true, features = [ "macros", "sync"] }
compio.workspace = true
futures.workspace = true
pin-project.workspace = true

async-stream = "0.3"
tracing-subscriber = "0.3"
cfg-if = "1"