[package]
name = "transport"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1"

bytes.workspace = true
futures-util = { version = "0.3", features = ["sink"] }

compio = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }

[features]
compio = ["dep:compio"]
tokio = ["dep:tokio", "dep:tokio-util"]