[package]
name = "transport"
version = "0.1.0"
edition = "2024"

[dependencies]
udt.path = "../udt"
snow = { version = "0.10", features = ["ring-accelerated"] }
range-set.workspace = true
parking_lot = "0.12"
scc = "2.3"
tracing.workspace = true