[package]
name = "util"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true

pin-project = "1.1"
snow = "0.10.0-alpha.1"